apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: webserver1
    build: ~/docker-data/alectrica/alectrica_site
    ports: 
     - containerPort: 4000
volumes:
  - name: websvr-storage
    emptyDir: {}


